trigger:
  branches:
    include:
    - outsystems
    - fix/yaml
pr: none

variables:
  SourcesDirectory: '$(Build.SourcesDirectory)'
  Project: 'requirejs'
  BuildConfiguration: 'Release'
  Config: '--configuration=$(BuildConfiguration)'
  CakePathLocation: '$(System.DefaultWorkingDirectory)'
  ReportDir: '$(Common.TestResultsDirectory)\coverage_report'
  TagName: 'v$(Build.BuildNumber)'
  
stages: 
- stage: Deploy
  displayName: 'Deploy'
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to npm private repository and creates a git release'
    timeoutInMinutes: 8
    pool:
      vmImage: 'ubuntu-latest'
    environment: Automatic-Release
    strategy: 
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: | 
              git fetch
              git switch fix/yaml
              git branch
              git pull
            displayName: Fetching assets
          #Restore the project packages
          - task: npmAuthenticate@0
            inputs:
              workingFile: '.npmrc'
              customEndpoint: 'NPM Authentication Token'
          - script: | 
              npm version prerelease --preid=outsystems --no-git-tag-version
              git branch --no-color --show-current
              $version = $(cat "package.json" | jq -r ".version")
              sed -i 's/version = "'.*'","/version = '$version'/g' require.js
              cat require.js
              grep -F "version = '.*'," require.js
            displayName: Bumping version
          - script: | 
              npm i -y
              npx uglifyjs require.js -mc --comments -o ./bin/r.js
              gc require.js | Select-String -Pattern "='$version',"
            displayName: Bundling requirejs
          - script: | 
              $newBranch = "bump/${version}"
              git checkout -b ${newBranch}
              git add -u
              git commit -m "[Pipeline] Bump version to ${newVersionNumber}"
              git push -u origin ${newBranch}
            displayName: Creating pull request
