name: Build and validate minify require.js

trigger: none
pr:
  branches:
    include:
    - '*'

stages: 
- stage: Build
  displayName: 'Build'
  jobs:
  - build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - script: | 
            npm i -y
            npx uglifyjs require.js -mc --comments -o ./output.txt
          displayName: Bundling requirejs
